@startuml diagrama de classes
'https://plantuml.com/class-diagram

Usuario <|-- Aluno
Usuario <|-- Professor
Aluno "0..*" --* "1..1" InstituicaoEnsino
Aluno -- Curso
Aluno "1..*"--* "0..*" Transação
Transação "0..*" -- "0..*" Vantagem
Professor "0..*" -- "0..*" Pagamento
Pagamento "0..*" *-- "0..*" Aluno
Professor "0..*" --* "1..1" InstituicaoEnsino
Professor "0..*" --* "1..1" Departamento : pertence a
Empresa "1..1" --o "0..*" Vantagem : oferece

class Usuario {
    - nome: String
    - CPF: String
    - login: String
    - senha: String
    + autenticar() : void
}

class Aluno{
    - RG: String
    - email: String
    - endereço: String
    - instituicaoEnsino: InstituicaoEnsino
    - curso: Curso
    - saldo: Int
    + cadastrar() : void
    + trocarMoedas(Vantagem vantagem) : Boolean
}

class Professor{
    - instituicaoEnsino : InstituicaoEnsino
    - departamento : Departamento
    - saldo: Int
    + atribuirMoedas(Aluno aluno): String
}



class Empresa{}
class InstituicaoEnsino{}
class Vantagem {
    -descrição: String
    -custo: Int
}

enum Curso {}
enum Departamento {}

@enduml