@startuml
left to right direction

actor "Aluno" as aluno
actor "Professor" as professor
actor "Empresa Parceira" as empresa

rectangle Sistema {
    usecase "Realizar Cadastro" as RealizarCadastroAluno
    usecase "Realizar Cadastro" as RealizarCadastroEmpresa
    usecase "Realizar Login" as RealizarLogin

    usecase "Distribuir Moedas" as DistribuirMoedas

    usecase "Consultar saldo e transações" as ConsultarSaldoAluno
    usecase "Consultar saldo e transações" as ConsultarSaldoProfessor

    usecase "Cadastrar vantagens" as CadastrarVantagem
    usecase "Trocar moedas por vantagens" as TrocarMoedas
    usecase "Enviar cupom para aluno e empresa" as EnviarCupom
}

aluno --> RealizarCadastroAluno
aluno --> RealizarLogin
aluno --> ConsultarSaldoAluno
aluno --> TrocarMoedas

professor --> RealizarLogin
professor --> DistribuirMoedas
professor --> ConsultarSaldoProfessor

empresa --> RealizarCadastroEmpresa
empresa --> RealizarLogin
empresa --> CadastrarVantagem

TrocarMoedas .> EnviarCupom : <<include>>

@enduml
